server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    ROOT: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
spring:
  datasource:
    maximumPoolSize: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/lol_leaderboard
    username: root
    password: secret
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate